// Use cases da timeline (RF §8, §9, §10, §11, §12, §13).

import { prisma } from "@/infrastructure/db";
import {
  ForbiddenError,
  NotFoundError,
  StateError,
  ValidationError
} from "@/shared/errors";
import { bus } from "@/infrastructure/sse-bus";
import { channels } from "@/application/sse-channels";
import { decideAutoRedOnYellow } from "@/domain/cards";
import { deriveScore } from "@/domain/score";
import { elapsedSeconds, formatClock } from "@/domain/clock";
import type { EventType, TimelineEvent as DomainEvent } from "@/shared/types";

interface SessionUser {
  id: string;
  role: "ORGANIZER" | "REFEREE";
}

const EVENT_TYPES_REGISTRABLE: EventType[] = [
  "gol",
  "gol_contra",
  "cartao_amarelo",
  "cartao_vermelho",
  "cartao_azul",
  "falta",
  "substituicao",
  "troca_goleiro"
];

async function loadActiveScoresheet(matchId: string, user: SessionUser) {
  const ss = await prisma.scoresheet.findUnique({
    where: { matchId },
    include: {
      match: { include: { round: { include: { championship: { include: { regulation: true } } } } } },
      timelineEvents: { orderBy: { recordedAt: "asc" } },
      presenceRecords: true
    }
  });
  if (!ss) throw new NotFoundError("Súmula não encontrada");
  if (ss.match.refereeUserId !== user.id) throw new ForbiddenError();
  if (ss.status === "salvo") throw new StateError("Súmula salva — peça reabertura ao organizador");
  if (ss.uiState !== "periodo_em_andamento") {
    throw new StateError("Eventos só podem ser registrados com o período em andamento");
  }
  return ss;
}

function currentClockLabel(periodStartedAt: Date | null): string {
  if (!periodStartedAt) return "00:00";
  return formatClock(elapsedSeconds(periodStartedAt));
}

export async function registerEvent(input: {
  matchId: string;
  user: SessionUser;
  type: EventType;
  teamId: string;
  playerId?: string | null;
  secondaryPlayerId?: string | null;
  clientEventId?: string;
}) {
  if (!EVENT_TYPES_REGISTRABLE.includes(input.type)) {
    throw new ValidationError("Tipo de evento inválido");
  }

  const ss = await loadActiveScoresheet(input.matchId, input.user);
  const match = ss.match;
  const reg = match.round.championship.regulation!;

  // Validações específicas por tipo
  if (input.teamId !== match.homeTeamId && input.teamId !== match.awayTeamId) {
    throw new ValidationError("Time não pertence ao jogo");
  }

  if (input.type === "cartao_azul" && reg.cardTypes !== "com_azul") {
    throw new ValidationError("Cartão azul não habilitado neste regulamento");
  }

  if (input.type !== "falta" && !input.playerId) {
    throw new ValidationError("playerId obrigatório para este tipo de evento");
  }

  if (input.playerId) {
    // Jogador deve estar presente para gols/cartões/sub/goleiro/etc.
    const presence = ss.presenceRecords.find((p) => p.playerId === input.playerId);
    if (!presence?.present) {
      throw new ValidationError("Jogador não está marcado como presente");
    }
  }

  if (input.type === "substituicao") {
    if (!input.secondaryPlayerId) {
      throw new ValidationError("Selecione o jogador que entra");
    }
    const enters = ss.presenceRecords.find((p) => p.playerId === input.secondaryPlayerId);
    if (!enters?.present) {
      throw new ValidationError("Jogador que entra deve estar presente");
    }
  }

  // Idempotência
  if (input.clientEventId) {
    const dup = await prisma.timelineEvent.findUnique({
      where: { clientEventId: input.clientEventId }
    });
    if (dup) return dup;
  }

  const clockLabel = currentClockLabel(ss.periodStartedAt);
  const period = ss.currentPeriod;

  // Cria evento principal
  const created = await prisma.timelineEvent.create({
    data: {
      scoresheetId: ss.id,
      type: input.type,
      clockLabel,
      playerId: input.playerId ?? null,
      teamId: input.teamId,
      secondaryPlayerId: input.secondaryPlayerId ?? null,
      period,
      clientEventId: input.clientEventId ?? null
    }
  });

  // Regra automática: 2º amarelo → vermelho automático (RF §10.4)
  if (input.type === "cartao_amarelo" && input.playerId) {
    const decision = decideAutoRedOnYellow(
      ss.timelineEvents as unknown as DomainEvent[],
      input.playerId
    );
    if (decision.shouldGenerate) {
      const auto = await prisma.timelineEvent.create({
        data: {
          scoresheetId: ss.id,
          type: "cartao_vermelho",
          clockLabel,
          playerId: input.playerId,
          teamId: input.teamId,
          period,
          autoGeneratedFromId: created.id
        }
      });
      // Suspensão por 2 amarelos
      await prisma.suspensionLog.create({
        data: {
          playerId: input.playerId,
          championshipId: match.round.championshipId,
          reason: "dois_amarelos",
          sourceMatchId: match.id,
          confirmed: false
        }
      });
      bus.emit(channels.orgAlerts(), "alert.suspension", {
        player_id: input.playerId,
        match_id: match.id,
        reason: "dois_amarelos"
      });
      bus.emit(channels.match(match.id), "match.event", {
        type: "cartao_vermelho",
        clock_label: clockLabel,
        period,
        player_id: input.playerId,
        auto_generated: true
      });
      // anexa o auto na resposta
      Object.assign(created, { autoGenerated: auto });
    }
  }

  // Vermelho direto → suspensão
  if (input.type === "cartao_vermelho" && input.playerId) {
    await prisma.suspensionLog.create({
      data: {
        playerId: input.playerId,
        championshipId: match.round.championshipId,
        reason: "vermelho_direto",
        sourceMatchId: match.id,
        confirmed: false
      }
    });
    bus.emit(channels.orgAlerts(), "alert.suspension", {
      player_id: input.playerId,
      match_id: match.id,
      reason: "vermelho_direto"
    });
  }

  // Atualiza placar derivado e dispara SSE
  await refreshDerivedScore(match.id);

  bus.emit(channels.match(match.id), "match.event", {
    type: input.type,
    clock_label: clockLabel,
    period,
    player_id: input.playerId ?? null,
    secondary_player_id: input.secondaryPlayerId ?? null,
    team_id: input.teamId,
    timestamp: created.recordedAt.toISOString()
  });

  return created;
}

export async function deleteEvent(input: {
  matchId: string;
  eventId: string;
  user: SessionUser;
}) {
  const ss = await loadActiveScoresheet(input.matchId, input.user);
  const event = ss.timelineEvents.find((e) => e.id === input.eventId);
  if (!event) throw new NotFoundError("Evento não encontrado");
  if (event.type === "inicio_periodo" || event.type === "fim_periodo") {
    throw new ValidationError("Eventos de período não podem ser excluídos manualmente");
  }

  // Se tinha vermelho automático ligado, remove junto (RF §10.4)
  const dependents = await prisma.timelineEvent.findMany({
    where: { autoGeneratedFromId: event.id }
  });
  await prisma.timelineEvent.deleteMany({ where: { autoGeneratedFromId: event.id } });
  await prisma.timelineEvent.delete({ where: { id: event.id } });

  // Limpa suspension_logs associados ao evento removido (best effort)
  if (event.type === "cartao_vermelho" && event.playerId) {
    await prisma.suspensionLog.deleteMany({
      where: {
        playerId: event.playerId,
        sourceMatchId: input.matchId,
        confirmed: false,
        reason: "vermelho_direto"
      }
    });
  }
  for (const dep of dependents) {
    if (dep.type === "cartao_vermelho" && dep.playerId) {
      await prisma.suspensionLog.deleteMany({
        where: {
          playerId: dep.playerId,
          sourceMatchId: input.matchId,
          confirmed: false,
          reason: "dois_amarelos"
        }
      });
    }
  }

  await refreshDerivedScore(input.matchId);
  bus.emit(channels.match(input.matchId), "match.event", {
    type: "delete",
    event_id: event.id
  });
  return { deleted: true };
}

export async function updateEvent(input: {
  matchId: string;
  eventId: string;
  user: SessionUser;
  patch: { teamId?: string; playerId?: string | null; type?: EventType };
}) {
  const ss = await loadActiveScoresheet(input.matchId, input.user);
  const event = ss.timelineEvents.find((e) => e.id === input.eventId);
  if (!event) throw new NotFoundError("Evento não encontrado");

  // RF §8.4: minutagem e period são imutáveis
  await prisma.timelineEvent.update({
    where: { id: event.id },
    data: {
      teamId: input.patch.teamId ?? undefined,
      playerId: input.patch.playerId === undefined ? undefined : input.patch.playerId,
      type: input.patch.type ?? undefined
    }
  });
  await refreshDerivedScore(input.matchId);
  return { updated: true };
}

export async function refreshDerivedScore(matchId: string) {
  const ss = await prisma.scoresheet.findUnique({
    where: { matchId },
    include: { match: true, timelineEvents: true }
  });
  if (!ss) return;
  const score = deriveScore(
    ss.timelineEvents as unknown as DomainEvent[],
    ss.match.homeTeamId,
    ss.match.awayTeamId
  );
  if (ss.homeScore !== score.homeScore || ss.awayScore !== score.awayScore) {
    await prisma.scoresheet.update({
      where: { id: ss.id },
      data: { homeScore: score.homeScore, awayScore: score.awayScore }
    });
    bus.emit(channels.match(matchId), "match.score", {
      home_score: score.homeScore,
      away_score: score.awayScore
    });
  }
}
