import { describe, it, expect } from "vitest";
import {
  countCardsForPlayer,
  decideAutoRedOnYellow,
  shouldGenerateAccumulationSuspension
} from "@/domain/cards";
import type { TimelineEvent } from "@/shared/types";

function ev(t: TimelineEvent["type"], playerId: string | null, id = "x"): TimelineEvent {
  return {
    id,
    scoresheetId: "ss",
    type: t,
    clockLabel: "00:00",
    playerId,
    teamId: "team",
    secondaryPlayerId: null,
    period: 1,
    recordedAt: new Date(),
    autoGeneratedFromId: null
  };
}

describe("cards", () => {
  it("conta cartões por jogador", () => {
    const events = [
      ev("cartao_amarelo", "p1"),
      ev("cartao_amarelo", "p1"),
      ev("cartao_vermelho", "p1"),
      ev("cartao_amarelo", "p2")
    ];
    expect(countCardsForPlayer(events, "p1")).toEqual({ yellow: 2, red: 1, blue: 0 });
    expect(countCardsForPlayer(events, "p2")).toEqual({ yellow: 1, red: 0, blue: 0 });
  });

  it("decideAutoRedOnYellow: 1º amarelo não gera (TC-SUM-018)", () => {
    expect(decideAutoRedOnYellow([], "p1")).toEqual({
      shouldGenerate: false,
      reason: null
    });
  });

  it("decideAutoRedOnYellow: 2º amarelo gera vermelho automático (TC-SUM-018)", () => {
    const events = [ev("cartao_amarelo", "p1", "y1")];
    const decision = decideAutoRedOnYellow(events, "p1");
    expect(decision.shouldGenerate).toBe(true);
    expect(decision.reason).toBe("dois_amarelos");
  });

  it("decideAutoRedOnYellow: amarelos de outros jogadores não influenciam", () => {
    const events = [ev("cartao_amarelo", "p2"), ev("cartao_amarelo", "p3")];
    expect(decideAutoRedOnYellow(events, "p1").shouldGenerate).toBe(false);
  });

  it("acúmulo de amarelos atinge limite gera suspensão ao salvar (TC-SUM-023)", () => {
    expect(
      shouldGenerateAccumulationSuspension({
        yellowAccumulationLimit: 3,
        previousYellowsAcrossChampionship: 2,
        yellowsInCurrentMatch: 1,
        alreadySuspendedFromMatch: false
      })
    ).toBe(true);
  });

  it("acúmulo: já suspenso por outro motivo neste jogo não gera novo", () => {
    expect(
      shouldGenerateAccumulationSuspension({
        yellowAccumulationLimit: 3,
        previousYellowsAcrossChampionship: 2,
        yellowsInCurrentMatch: 1,
        alreadySuspendedFromMatch: true
      })
    ).toBe(false);
  });

  it("acúmulo abaixo do limite não gera", () => {
    expect(
      shouldGenerateAccumulationSuspension({
        yellowAccumulationLimit: 3,
        previousYellowsAcrossChampionship: 1,
        yellowsInCurrentMatch: 1,
        alreadySuspendedFromMatch: false
      })
    ).toBe(false);
  });
});
