import { describe, it, expect } from "vitest";
import {
  countTeamFoulsInPeriod,
  countPlayerFoulsInMatch,
  teamFoulVisualState
} from "@/domain/fouls";
import type { TimelineEvent } from "@/shared/types";

function falta(teamId: string, playerId: string | null, period = 1): TimelineEvent {
  return {
    id: Math.random().toString(),
    scoresheetId: "ss",
    type: "falta",
    clockLabel: "10:00",
    playerId,
    teamId,
    secondaryPlayerId: null,
    period,
    recordedAt: new Date(),
    autoGeneratedFromId: null
  };
}

describe("fouls", () => {
  it("conta faltas por time por período (TC-SUM-027, TC-SUM-028)", () => {
    const events = [
      falta("A", "p1", 1),
      falta("A", "p2", 1),
      falta("B", "p3", 1),
      falta("A", null, 2)
    ];
    expect(countTeamFoulsInPeriod(events, "A", 1)).toBe(2);
    expect(countTeamFoulsInPeriod(events, "B", 1)).toBe(1);
    expect(countTeamFoulsInPeriod(events, "A", 2)).toBe(1);
  });

  it("conta faltas por jogador no jogo todo", () => {
    const events = [falta("A", "p1", 1), falta("A", "p1", 2), falta("A", "p2", 2)];
    expect(countPlayerFoulsInMatch(events, "p1")).toBe(2);
  });

  it("estado visual: neutro (0–3), alerta (limit-1=4), tiro_livre (≥5)", () => {
    expect(teamFoulVisualState(0, 5)).toBe("neutro");
    expect(teamFoulVisualState(3, 5)).toBe("neutro");
    expect(teamFoulVisualState(4, 5)).toBe("alerta");
    expect(teamFoulVisualState(5, 5)).toBe("tiro_livre");
    expect(teamFoulVisualState(7, 5)).toBe("tiro_livre");
  });
});
