import { describe, it, expect } from "vitest";
import { computeGoalkeeperTimeForTeam } from "@/domain/goalkeeper";
import type { TimelineEvent } from "@/shared/types";

const TEAM = "team-x";

function trocaGoleiro(playerIn: string, clockLabel: string, period = 1): TimelineEvent {
  return {
    id: Math.random().toString(),
    scoresheetId: "ss",
    type: "troca_goleiro",
    clockLabel,
    playerId: playerIn,
    teamId: TEAM,
    secondaryPlayerId: null,
    period,
    recordedAt: new Date(),
    autoGeneratedFromId: null
  };
}

describe("goalkeeper time", () => {
  it("sem trocas: goleiro inicial joga o jogo inteiro (TC-SUM-032)", () => {
    const result = computeGoalkeeperTimeForTeam({
      teamId: TEAM,
      initialGoalkeeperPlayerId: "g1",
      events: [],
      periodEndSecondsByPeriod: { 1: 20 * 60, 2: 20 * 60 }
    });
    expect(result).toEqual([{ playerId: "g1", totalSeconds: 40 * 60 }]);
  });

  it("uma troca no 2º período (TC-SUM-032)", () => {
    // 1º período: g1 do 0-20:00 (1200s)
    // 2º período: g1 do 0-11:00 (660s) e g2 do 11:00-14:00 (180s) = 840s
    const result = computeGoalkeeperTimeForTeam({
      teamId: TEAM,
      initialGoalkeeperPlayerId: "g1",
      events: [trocaGoleiro("g2", "11:00", 2)],
      periodEndSecondsByPeriod: { 1: 20 * 60, 2: 14 * 60 }
    });
    const g1 = result.find((r) => r.playerId === "g1");
    const g2 = result.find((r) => r.playerId === "g2");
    expect(g1?.totalSeconds).toBe(1200 + 11 * 60);
    expect(g2?.totalSeconds).toBe(3 * 60);
  });

  it("múltiplas trocas no mesmo período", () => {
    // período 1 (10min): g1 0-3:00, g2 3:00-7:00, g3 7:00-10:00
    const result = computeGoalkeeperTimeForTeam({
      teamId: TEAM,
      initialGoalkeeperPlayerId: "g1",
      events: [trocaGoleiro("g2", "03:00", 1), trocaGoleiro("g3", "07:00", 1)],
      periodEndSecondsByPeriod: { 1: 10 * 60 }
    });
    const find = (id: string) => result.find((r) => r.playerId === id)?.totalSeconds ?? 0;
    expect(find("g1")).toBe(3 * 60);
    expect(find("g2")).toBe(4 * 60);
    expect(find("g3")).toBe(3 * 60);
  });

  it("ignora trocas de outros times", () => {
    const evOtherTeam: TimelineEvent = {
      id: "x",
      scoresheetId: "ss",
      type: "troca_goleiro",
      clockLabel: "05:00",
      playerId: "ggg",
      teamId: "outro",
      secondaryPlayerId: null,
      period: 1,
      recordedAt: new Date(),
      autoGeneratedFromId: null
    };
    const result = computeGoalkeeperTimeForTeam({
      teamId: TEAM,
      initialGoalkeeperPlayerId: "g1",
      events: [evOtherTeam],
      periodEndSecondsByPeriod: { 1: 10 * 60 }
    });
    expect(result).toEqual([{ playerId: "g1", totalSeconds: 10 * 60 }]);
  });
});
