import { describe, it, expect } from "vitest";
import { deriveScore } from "@/domain/score";
import type { TimelineEvent } from "@/shared/types";

const HOME = "team-home";
const AWAY = "team-away";

function ev(partial: Partial<TimelineEvent> & Pick<TimelineEvent, "type" | "teamId">): TimelineEvent {
  return {
    id: partial.id ?? "ev-" + Math.random(),
    scoresheetId: partial.scoresheetId ?? "ss",
    type: partial.type,
    clockLabel: partial.clockLabel ?? "00:00",
    playerId: partial.playerId ?? null,
    teamId: partial.teamId,
    secondaryPlayerId: partial.secondaryPlayerId ?? null,
    period: partial.period ?? 1,
    recordedAt: partial.recordedAt ?? new Date(),
    autoGeneratedFromId: partial.autoGeneratedFromId ?? null
  };
}

describe("deriveScore", () => {
  it("placar zero quando timeline vazia (TC-GLB-003)", () => {
    expect(deriveScore([], HOME, AWAY)).toEqual({ homeScore: 0, awayScore: 0 });
  });

  it("gol normal soma para o time do evento (TC-SUM-014)", () => {
    const events = [
      ev({ type: "gol", teamId: HOME, playerId: "p1" }),
      ev({ type: "gol", teamId: HOME, playerId: "p2" })
    ];
    expect(deriveScore(events, HOME, AWAY)).toEqual({ homeScore: 2, awayScore: 0 });
  });

  it("gol contra: ponto vai para o adversário (TC-SUM-015)", () => {
    const events = [ev({ type: "gol_contra", teamId: AWAY, playerId: "p3" })];
    expect(deriveScore(events, HOME, AWAY)).toEqual({ homeScore: 1, awayScore: 0 });
  });

  it("excluir gol decrementa placar (TC-SUM-017 / RF §11.2)", () => {
    const before = [
      ev({ type: "gol", teamId: HOME, playerId: "p1" }),
      ev({ type: "gol", teamId: AWAY, playerId: "p2" })
    ];
    const after = before.filter((e) => e.playerId !== "p1");
    expect(deriveScore(before, HOME, AWAY)).toEqual({ homeScore: 1, awayScore: 1 });
    expect(deriveScore(after, HOME, AWAY)).toEqual({ homeScore: 0, awayScore: 1 });
  });

  it("ignora outros tipos de evento", () => {
    const events = [
      ev({ type: "cartao_amarelo", teamId: HOME, playerId: "p1" }),
      ev({ type: "falta", teamId: HOME, playerId: "p1" })
    ];
    expect(deriveScore(events, HOME, AWAY)).toEqual({ homeScore: 0, awayScore: 0 });
  });
});
