import { auth } from "@/infrastructure/auth";
import { getMatchForReferee } from "@/application/use-cases/matches";
import { getOrCreateScoresheet } from "@/application/use-cases/scoresheet";
import { ScoresheetScreen } from "./scoresheet-screen";
import { regulationFromDb } from "@/application/use-cases/championship";

export const dynamic = "force-dynamic";

export default async function MatchSumulaPage({
  params
}: {
  params: { id: string };
}) {
  const session = await auth();
  const userId = session!.user.id;

  let match = await getMatchForReferee(params.id, userId);
  if (!match.scoresheet) {
    await getOrCreateScoresheet(match.id, { id: userId, role: "REFEREE" });
    match = await getMatchForReferee(params.id, userId);
  }

  const regulation = match.round.championship.regulation
    ? regulationFromDb(match.round.championship.regulation)
    : null;

  return (
    <ScoresheetScreen
      matchId={match.id}
      home={{
        id: match.homeTeamId,
        name: match.homeTeam.name,
        color: match.homeTeam.color ?? "#0088CC",
        players: match.homeTeam.players.map((p) => ({
          id: p.id,
          fullName: p.fullName,
          status: p.status
        }))
      }}
      away={{
        id: match.awayTeamId,
        name: match.awayTeam.name,
        color: match.awayTeam.color ?? "#0D1117",
        players: match.awayTeam.players.map((p) => ({
          id: p.id,
          fullName: p.fullName,
          status: p.status
        }))
      }}
      championshipName={match.round.championship.name}
      modality={match.round.championship.modality}
      regulation={regulation}
      initialScoresheet={match.scoresheet ? serializeScoresheet(match.scoresheet) : null}
      refereeName={match.refereeNameText ?? null}
      homeResponsible={match.homeResponsible ?? null}
      awayResponsible={match.awayResponsible ?? null}
      scheduledAt={match.scheduledAt.toISOString()}
      venue={match.venue ?? null}
    />
  );
}

function serializeScoresheet(ss: NonNullable<Awaited<ReturnType<typeof getMatchForReferee>>["scoresheet"]>) {
  return {
    id: ss.id,
    status: ss.status,
    uiState: ss.uiState,
    currentPeriod: ss.currentPeriod,
    periodStartedAt: ss.periodStartedAt?.toISOString() ?? null,
    homeScore: ss.homeScore,
    awayScore: ss.awayScore,
    homeGoalkeeperPlayerId: ss.homeGoalkeeperPlayerId,
    awayGoalkeeperPlayerId: ss.awayGoalkeeperPlayerId,
    homeGoalkeeperAvulso: ss.homeGoalkeeperAvulsoName
      ? { name: ss.homeGoalkeeperAvulsoName, jersey: ss.homeGoalkeeperAvulsoJersey ?? 0 }
      : null,
    awayGoalkeeperAvulso: ss.awayGoalkeeperAvulsoName
      ? { name: ss.awayGoalkeeperAvulsoName, jersey: ss.awayGoalkeeperAvulsoJersey ?? 0 }
      : null,
    presence: ss.presenceRecords.map((p) => ({
      playerId: p.playerId,
      jerseyNumber: p.jerseyNumber,
      present: p.present,
      absenceType: p.absenceType,
      isGoalkeeper: p.isGoalkeeper
    })),
    timeline: ss.timelineEvents.map((e) => ({
      id: e.id,
      type: e.type,
      clockLabel: e.clockLabel,
      playerId: e.playerId,
      teamId: e.teamId,
      secondaryPlayerId: e.secondaryPlayerId,
      period: e.period,
      autoGeneratedFromId: e.autoGeneratedFromId,
      recordedAt: e.recordedAt.toISOString()
    })),
    penaltyShoot: ss.penaltyShoot
      ? {
          homeScore: ss.penaltyShoot.homeScore,
          awayScore: ss.penaltyShoot.awayScore,
          finished: ss.penaltyShoot.finished,
          kicks: ss.penaltyShoot.kicks.map((k) => ({
            id: k.id,
            teamId: k.teamId,
            playerId: k.playerId,
            kickOrder: k.kickOrder,
            converted: k.converted
          }))
        }
      : null,
    shareDocText: ss.shareDocText
  };
}
