"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { RegulationData } from "@/shared/types";
import {
  countTeamFoulsInPeriod,
  countPlayerFoulsInMatch,
  teamFoulVisualState
} from "@/domain/fouls";
import { computePenaltyState } from "@/domain/penalty";
import { deriveScore } from "@/domain/score";

interface PlayerLite {
  id: string;
  fullName: string;
  status: string;
}

interface TeamLite {
  id: string;
  name: string;
  color: string;
  players: PlayerLite[];
}

interface PresenceLite {
  playerId: string;
  jerseyNumber: number | null;
  present: boolean;
  absenceType: string | null;
  isGoalkeeper: boolean;
}

interface TimelineEventLite {
  id: string;
  type: string;
  clockLabel: string;
  playerId: string | null;
  teamId: string;
  secondaryPlayerId: string | null;
  period: number;
  autoGeneratedFromId: string | null;
  recordedAt: string;
}

interface ScoresheetLite {
  id: string;
  status: string;
  uiState: string;
  currentPeriod: number;
  periodStartedAt: string | null;
  homeScore: number;
  awayScore: number;
  homeGoalkeeperPlayerId: string | null;
  awayGoalkeeperPlayerId: string | null;
  homeGoalkeeperAvulso: { name: string; jersey: number } | null;
  awayGoalkeeperAvulso: { name: string; jersey: number } | null;
  presence: PresenceLite[];
  timeline: TimelineEventLite[];
  penaltyShoot: {
    homeScore: number;
    awayScore: number;
    finished: boolean;
    kicks: { id: string; teamId: string; playerId: string | null; kickOrder: number; converted: boolean }[];
  } | null;
  shareDocText: string | null;
}

interface Props {
  matchId: string;
  home: TeamLite;
  away: TeamLite;
  championshipName: string;
  modality: string;
  regulation: RegulationData | null;
  initialScoresheet: ScoresheetLite | null;
  refereeName: string | null;
  homeResponsible: string | null;
  awayResponsible: string | null;
  scheduledAt: string;
  venue: string | null;
}

function formatClock(seconds: number) {
  const mm = Math.floor(seconds / 60);
  const ss = seconds % 60;
  return `${String(mm).padStart(2, "0")}:${String(ss).padStart(2, "0")}`;
}

export function ScoresheetScreen(props: Props) {
  const router = useRouter();
  const [ss, setSs] = useState<ScoresheetLite>(
    props.initialScoresheet ?? defaultEmptyScoresheet()
  );
  const [tab, setTab] = useState<"timeline" | "presence" | "elenco">("timeline");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [now, setNow] = useState(Date.now());
  const [absenceModal, setAbsenceModal] = useState<{ playerId: string } | null>(null);
  const [eventModal, setEventModal] = useState<EventModalState | null>(null);
  const [endPeriodModal, setEndPeriodModal] = useState(false);
  const [saveModal, setSaveModal] = useState(false);
  const [occurrenceModal, setOccurrenceModal] = useState(false);

  // Tick crônico
  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  // SSE
  useEffect(() => {
    const es = new EventSource(`/api/sse/match/${props.matchId}`);
    const refresh = () => fetchState();
    es.addEventListener("match.event", refresh);
    es.addEventListener("match.score", refresh);
    es.addEventListener("match.status", refresh);
    es.addEventListener("match.penalty", refresh);
    es.addEventListener("match.saved", refresh);
    return () => es.close();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.matchId]);

  async function fetchState() {
    const res = await fetch(`/api/sumula/matches/${props.matchId}`);
    if (!res.ok) return;
    const data = await res.json();
    if (data.scoresheet) setSs(serialize(data.scoresheet));
  }

  // ===== Derivações =====
  const elapsedSec = ss.periodStartedAt
    ? Math.max(0, Math.floor((now - new Date(ss.periodStartedAt).getTime()) / 1000))
    : 0;
  const clockLabel = formatClock(elapsedSec);
  const overTime =
    !!props.regulation &&
    elapsedSec >= (props.regulation.periodDurationMin ?? 20) * 60;

  const score = useMemo(
    () => deriveScore(ss.timeline as any, props.home.id, props.away.id),
    [ss.timeline, props.home.id, props.away.id]
  );

  const homeFouls = useMemo(
    () => countTeamFoulsInPeriod(ss.timeline as any, props.home.id, ss.currentPeriod),
    [ss.timeline, props.home.id, ss.currentPeriod]
  );
  const awayFouls = useMemo(
    () => countTeamFoulsInPeriod(ss.timeline as any, props.away.id, ss.currentPeriod),
    [ss.timeline, props.away.id, ss.currentPeriod]
  );

  const homeGoalkeeperPresence = ss.presence.find(
    (p) => p.playerId === ss.homeGoalkeeperPlayerId && p.present
  );
  const awayGoalkeeperPresence = ss.presence.find(
    (p) => p.playerId === ss.awayGoalkeeperPlayerId && p.present
  );

  const playerById = useMemo(() => {
    const map = new Map<string, PlayerLite & { teamId: string }>();
    for (const p of props.home.players) map.set(p.id, { ...p, teamId: props.home.id });
    for (const p of props.away.players) map.set(p.id, { ...p, teamId: props.away.id });
    return map;
  }, [props.home, props.away]);

  // ===== Ações =====
  async function action(url: string, body?: unknown, method: "POST" | "PATCH" | "DELETE" = "POST") {
    setErrorMsg(null);
    const res = await fetch(url, {
      method,
      headers: { "Content-Type": "application/json" },
      body: body ? JSON.stringify(body) : undefined
    });
    if (!res.ok) {
      const j = await res.json().catch(() => ({}));
      setErrorMsg(j.message ?? "Erro");
    }
    await fetchState();
    return res.ok;
  }

  async function togglePresence(p: PresenceLite) {
    if (p.present) {
      // Abrir modal de ausência
      setAbsenceModal({ playerId: p.playerId });
    } else {
      await action(`/api/sumula/matches/${props.matchId}/presence`, {
        playerId: p.playerId,
        present: true,
        jerseyNumber: p.jerseyNumber ?? null
      }, "PATCH");
    }
  }

  async function setJersey(playerId: string, value: number | null) {
    await action(`/api/sumula/matches/${props.matchId}/presence`, {
      playerId,
      present: true,
      jerseyNumber: value
    }, "PATCH");
  }

  async function startPeriod() {
    await action(`/api/sumula/matches/${props.matchId}/period`, { action: "start" });
  }
  async function endPeriod() {
    await action(`/api/sumula/matches/${props.matchId}/period`, { action: "end" });
    setEndPeriodModal(false);
  }
  async function reopenPeriod() {
    await action(`/api/sumula/matches/${props.matchId}/period`, { action: "reopen" });
  }
  async function backToPeriod() {
    await action(`/api/sumula/matches/${props.matchId}/period`, { action: "back_to_period" });
  }

  async function saveScoresheet() {
    const r = await fetch(`/api/sumula/matches/${props.matchId}/save`, { method: "POST" });
    if (!r.ok) {
      const j = await r.json().catch(() => ({}));
      setErrorMsg(j.message ?? "Erro ao salvar");
    } else {
      const data = await r.json();
      // Compartilhamento nativo (RF §16.2)
      if (typeof navigator !== "undefined" && (navigator as Navigator & { share?: (d: ShareData) => Promise<void> }).share) {
        try {
          await (navigator as Navigator & { share?: (d: ShareData) => Promise<void> }).share!({
            title: `Súmula — ${props.home.name} × ${props.away.name}`,
            text: data.shareDocText,
            url: typeof window !== "undefined" ? window.location.href : ""
          });
        } catch {
          // ignored — usuário cancelou
        }
      }
      setSaveModal(false);
      await fetchState();
      router.refresh();
    }
  }

  async function setInitialGoalkeeper(side: "home" | "away", playerId?: string, avulso?: { name: string; jersey: number }) {
    await action(`/api/sumula/matches/${props.matchId}/goalkeeper`, { side, playerId, avulso }, "PATCH");
  }

  async function deleteEvent(id: string) {
    await action(`/api/sumula/matches/${props.matchId}/events/${id}`, undefined, "DELETE");
  }

  async function registerEvent(args: {
    type: string;
    teamId: string;
    playerId?: string | null;
    secondaryPlayerId?: string | null;
  }) {
    await action(`/api/sumula/matches/${props.matchId}/events`, args);
  }

  async function recordPenaltyKick(teamId: string, playerId: string, converted: boolean) {
    await action(`/api/sumula/matches/${props.matchId}/penalty`, {
      action: "record",
      teamId,
      playerId,
      converted
    });
  }
  async function undoLastPenaltyKick() {
    await action(`/api/sumula/matches/${props.matchId}/penalty`, { action: "undo" });
  }
  async function confirmPenaltyResult() {
    await action(`/api/sumula/matches/${props.matchId}/penalty`, { action: "confirm" });
  }

  async function recordOccurrence(type: string, description: string, players: string[]) {
    await action(`/api/sumula/matches/${props.matchId}/occurrence`, {
      type,
      description,
      playersInvolved: players
    });
    setOccurrenceModal(false);
  }

  // ===== Validações de UI =====
  const canStart =
    ss.uiState === "pre_jogo" &&
    !ss.presence.some((p) => p.present && (p.jerseyNumber === null || p.jerseyNumber === undefined));

  // ============================================================
  // RENDER
  // ============================================================
  return (
    <div className="max-w-md mx-auto pb-24">
      {/* Topbar */}
      <div className="bg-ink text-white text-xs px-3 py-2 flex justify-between">
        <span>
          {props.championshipName} · {props.modality}
        </span>
        <span className="bg-alert/90 px-2 py-0.5 rounded">
          {ss.uiState === "pre_jogo"
            ? "Pré-jogo"
            : ss.uiState === "periodo_em_andamento"
              ? "Em jogo"
              : ss.uiState === "intervalo"
                ? "Intervalo"
                : ss.uiState === "modal_penaltis"
                  ? "Pênaltis"
                  : ss.uiState === "em_revisao"
                    ? "Revisão"
                    : ss.uiState === "encerrado"
                      ? "Encerrada"
                      : ss.uiState}
        </span>
      </div>

      {/* Scoreboard */}
      <div className="bg-primary-700 text-white px-4 py-4 sticky top-0 z-10 shadow-md">
        <div className="text-center text-xs opacity-80 mb-1">
          {ss.currentPeriod > 0 && `${ss.currentPeriod}º período`}
        </div>
        <div className="flex items-center justify-between gap-3">
          <TeamScoreColumn
            name={props.home.name}
            color={props.home.color}
            score={score.homeScore}
          />
          <div
            className={`text-4xl font-extrabold tabular-nums ${
              overTime ? "text-danger animate-pulse" : ""
            }`}
            aria-live="polite"
          >
            {clockLabel}
          </div>
          <TeamScoreColumn
            name={props.away.name}
            color={props.away.color}
            score={score.awayScore}
            reverse
          />
        </div>
        {props.regulation && ss.uiState === "periodo_em_andamento" && (
          <div className="mt-2 h-1.5 bg-primary-900 rounded">
            <div
              className={`h-full rounded ${overTime ? "bg-danger" : "bg-primary-200"}`}
              style={{
                width: `${Math.min(
                  100,
                  (elapsedSec / (props.regulation.periodDurationMin * 60)) * 100
                )}%`
              }}
            />
          </div>
        )}
      </div>

      {/* Falta por time */}
      {props.regulation?.foulFreeKickEnabled &&
        ss.uiState === "periodo_em_andamento" && (
          <div className="grid grid-cols-2 gap-2 px-3 py-2 bg-white border-b border-surface-100">
            <FoulChip
              count={homeFouls}
              limit={props.regulation.foulFreeKickLimit}
              teamName={props.home.name}
            />
            <FoulChip
              count={awayFouls}
              limit={props.regulation.foulFreeKickLimit}
              teamName={props.away.name}
            />
          </div>
        )}

      {/* CONTEÚDO POR ESTADO */}
      {ss.uiState === "pre_jogo" && (
        <PreGameView
          home={props.home}
          away={props.away}
          presence={ss.presence}
          regulation={props.regulation}
          championshipName={props.championshipName}
          refereeName={props.refereeName}
          homeResponsible={props.homeResponsible}
          awayResponsible={props.awayResponsible}
          scheduledAt={props.scheduledAt}
          venue={props.venue}
          homeGoalkeeperPlayerId={ss.homeGoalkeeperPlayerId}
          awayGoalkeeperPlayerId={ss.awayGoalkeeperPlayerId}
          onTogglePresence={togglePresence}
          onSetJersey={setJersey}
          onSetInitialGoalkeeper={setInitialGoalkeeper}
          onStart={startPeriod}
          canStart={canStart}
        />
      )}

      {ss.uiState === "intervalo" && (
        <div className="px-4 py-6 text-center">
          <p className="text-muted mb-4">
            Intervalo · {ss.currentPeriod}º período encerrado
          </p>
          <div className="flex gap-3">
            <button
              onClick={reopenPeriod}
              className="flex-1 rounded bg-surface-100 py-3 font-semibold"
            >
              Reabrir período
            </button>
            <button
              onClick={startPeriod}
              className="flex-1 rounded bg-primary-500 text-white py-3 font-semibold"
            >
              Iniciar {ss.currentPeriod + 1}º período
            </button>
          </div>
        </div>
      )}

      {(ss.uiState === "periodo_em_andamento" || ss.uiState === "reaberto") && (
        <PeriodView
          home={props.home}
          away={props.away}
          presence={ss.presence}
          ss={ss}
          regulation={props.regulation}
          tab={tab}
          setTab={setTab}
          onTrigger={(state) => setEventModal(state)}
          onDelete={deleteEvent}
          onTogglePresence={togglePresence}
          onSetJersey={setJersey}
          onChangeGoalkeeper={(side) =>
            setEventModal({
              kind: "troca_goleiro",
              teamId: side === "home" ? props.home.id : props.away.id
            })
          }
          onEndPeriod={() => setEndPeriodModal(true)}
          playerById={playerById}
        />
      )}

      {ss.uiState === "modal_penaltis" && (
        <PenaltyView
          ss={ss}
          home={props.home}
          away={props.away}
          regulation={props.regulation}
          onRecord={recordPenaltyKick}
          onUndo={undoLastPenaltyKick}
          onConfirm={confirmPenaltyResult}
        />
      )}

      {ss.uiState === "em_revisao" && (
        <ReviewView
          ss={ss}
          home={props.home}
          away={props.away}
          championshipName={props.championshipName}
          refereeName={props.refereeName}
          homeResponsible={props.homeResponsible}
          awayResponsible={props.awayResponsible}
          scheduledAt={props.scheduledAt}
          venue={props.venue}
          playerById={playerById}
          onBack={backToPeriod}
          onSave={() => setSaveModal(true)}
          onRegisterOccurrence={() => setOccurrenceModal(true)}
        />
      )}

      {ss.uiState === "encerrado" && (
        <div className="px-4 py-6 text-center">
          <p className="text-success font-semibold mb-2">Súmula salva.</p>
          <p className="text-sm text-muted whitespace-pre-wrap text-left bg-white border border-surface-100 rounded-lg p-3 mt-4">
            {ss.shareDocText}
          </p>
        </div>
      )}

      {errorMsg && (
        <div className="fixed bottom-3 left-3 right-3 z-30 bg-danger text-white p-3 rounded-lg text-sm">
          {errorMsg}
        </div>
      )}

      {/* MODAIS */}
      {absenceModal && (
        <AbsenceModal
          onConfirm={async (absenceType) => {
            await action(
              `/api/sumula/matches/${props.matchId}/presence`,
              {
                playerId: absenceModal.playerId,
                present: false,
                absenceType
              },
              "PATCH"
            );
            setAbsenceModal(null);
          }}
          onClose={() => setAbsenceModal(null)}
          player={playerById.get(absenceModal.playerId) ?? null}
        />
      )}

      {eventModal && (
        <EventModal
          state={eventModal}
          ss={ss}
          home={props.home}
          away={props.away}
          regulation={props.regulation}
          playerById={playerById}
          onClose={() => setEventModal(null)}
          onConfirm={async (args) => {
            await registerEvent(args);
            setEventModal(null);
          }}
        />
      )}

      {endPeriodModal && (
        <ConfirmModal
          title={`Encerrar ${ss.currentPeriod}º período?`}
          message={`Minutagem atual: ${clockLabel}${
            overTime
              ? ` — ${formatClock(elapsedSec - props.regulation!.periodDurationMin * 60)} de acréscimo`
              : ""
          }. Esta ação registra o fim do período na timeline.`}
          confirmLabel="Encerrar"
          danger
          onConfirm={endPeriod}
          onCancel={() => setEndPeriodModal(false)}
        />
      )}

      {saveModal && (
        <ConfirmModal
          title="Salvar súmula?"
          message="Após salvar, apenas o organizador pode editar. Esta ação é irreversível para você."
          confirmLabel="Salvar"
          danger={false}
          onConfirm={saveScoresheet}
          onCancel={() => setSaveModal(false)}
        />
      )}

      {occurrenceModal && (
        <OccurrenceModal
          players={[...props.home.players, ...props.away.players]}
          onClose={() => setOccurrenceModal(false)}
          onConfirm={recordOccurrence}
        />
      )}
    </div>
  );
}

// ============================================================
// SUB-VIEWS
// ============================================================

function TeamScoreColumn({
  name,
  color,
  score,
  reverse
}: {
  name: string;
  color: string;
  score: number;
  reverse?: boolean;
}) {
  return (
    <div className={`flex items-center gap-2 ${reverse ? "flex-row-reverse" : ""}`}>
      <div
        className="w-8 h-8 rounded-full border-2 border-white"
        style={{ background: color }}
      />
      <div className={reverse ? "text-right" : ""}>
        <div className="text-[10px] uppercase tracking-wide opacity-80 max-w-[80px] truncate">
          {name}
        </div>
        <div className="text-2xl font-bold tabular-nums">{score}</div>
      </div>
    </div>
  );
}

function FoulChip({
  count,
  limit,
  teamName
}: {
  count: number;
  limit: number;
  teamName: string;
}) {
  const state = teamFoulVisualState(count, limit);
  const cls =
    state === "tiro_livre"
      ? "bg-danger/10 text-danger"
      : state === "alerta"
        ? "bg-alert/10 text-alert"
        : "bg-surface-100 text-muted";
  return (
    <div className={`rounded px-2 py-1 text-xs ${cls}`}>
      <span className="font-semibold">{teamName}</span>: {count} faltas
      {state === "alerta" && " · próx. = tiro livre"}
      {state === "tiro_livre" && " · TIRO LIVRE!"}
    </div>
  );
}

function PreGameView(props: {
  home: TeamLite;
  away: TeamLite;
  presence: PresenceLite[];
  regulation: RegulationData | null;
  championshipName: string;
  refereeName: string | null;
  homeResponsible: string | null;
  awayResponsible: string | null;
  scheduledAt: string;
  venue: string | null;
  homeGoalkeeperPlayerId: string | null;
  awayGoalkeeperPlayerId: string | null;
  onTogglePresence: (p: PresenceLite) => void;
  onSetJersey: (playerId: string, value: number | null) => void;
  onSetInitialGoalkeeper: (
    side: "home" | "away",
    playerId?: string,
    avulso?: { name: string; jersey: number }
  ) => void;
  onStart: () => void;
  canStart: boolean;
}) {
  return (
    <div className="px-4 py-4 space-y-4">
      <section className="bg-white rounded-lg border border-surface-100 p-4 text-sm space-y-1">
        <div className="text-muted">{props.championshipName}</div>
        <div className="font-semibold text-base">
          {props.home.name} × {props.away.name}
        </div>
        <div>{new Date(props.scheduledAt).toLocaleString("pt-BR")}</div>
        {props.venue && <div>Local: {props.venue}</div>}
        {props.refereeName && <div>Árbitro: {props.refereeName}</div>}
        {props.homeResponsible && <div>Resp. {props.home.name}: {props.homeResponsible}</div>}
        {props.awayResponsible && <div>Resp. {props.away.name}: {props.awayResponsible}</div>}
        {props.regulation && (
          <div className="text-muted">
            {props.regulation.numPeriods}× {props.regulation.periodDurationMin}min
          </div>
        )}
      </section>

      {[props.home, props.away].map((team) => {
        const isHome = team.id === props.home.id;
        const goalkeeperId = isHome ? props.homeGoalkeeperPlayerId : props.awayGoalkeeperPlayerId;
        return (
          <PresenceTeamSection
            key={team.id}
            team={team}
            presence={props.presence}
            goalkeeperId={goalkeeperId}
            onTogglePresence={props.onTogglePresence}
            onSetJersey={props.onSetJersey}
            onSelectGoalkeeper={(playerId, avulso) =>
              props.onSetInitialGoalkeeper(isHome ? "home" : "away", playerId, avulso)
            }
          />
        );
      })}

      <button
        onClick={props.onStart}
        disabled={!props.canStart}
        className="w-full rounded-lg bg-primary-500 text-white py-4 font-semibold text-lg disabled:opacity-50 disabled:cursor-not-allowed touch-48"
      >
        Iniciar 1º período
      </button>
      {!props.canStart && (
        <p className="text-xs text-danger text-center">
          Há jogadores presentes sem número de camisa.
        </p>
      )}
    </div>
  );
}

function PresenceTeamSection({
  team,
  presence,
  goalkeeperId,
  onTogglePresence,
  onSetJersey,
  onSelectGoalkeeper
}: {
  team: TeamLite;
  presence: PresenceLite[];
  goalkeeperId: string | null;
  onTogglePresence: (p: PresenceLite) => void;
  onSetJersey: (playerId: string, value: number | null) => void;
  onSelectGoalkeeper: (playerId?: string, avulso?: { name: string; jersey: number }) => void;
}) {
  const [showAvulso, setShowAvulso] = useState(false);
  const [avulsoName, setAvulsoName] = useState("");
  const [avulsoJersey, setAvulsoJersey] = useState("");

  const presents = presence.filter((p) => p.present && team.players.find((tp) => tp.id === p.playerId));

  return (
    <section className="bg-white rounded-lg border border-surface-100">
      <div
        className="px-3 py-2 text-white text-sm font-semibold rounded-t-lg flex justify-between items-center"
        style={{ background: team.color }}
      >
        <span>{team.name}</span>
        <select
          value={goalkeeperId ?? ""}
          onChange={(e) => onSelectGoalkeeper(e.target.value || undefined)}
          className="text-ink text-xs rounded px-2 py-1"
        >
          <option value="">Goleiro inicial…</option>
          {presents.map((p) => {
            const player = team.players.find((tp) => tp.id === p.playerId)!;
            return (
              <option key={p.playerId} value={p.playerId}>
                #{p.jerseyNumber ?? "—"} {player.fullName}
              </option>
            );
          })}
        </select>
      </div>

      <ul className="divide-y divide-surface-100">
        {team.players
          .filter((p) => p.status !== "inativo")
          .map((player) => {
            const rec =
              presence.find((p) => p.playerId === player.id) ?? {
                playerId: player.id,
                jerseyNumber: null,
                present: false,
                absenceType: null,
                isGoalkeeper: false
              };
            return (
              <li key={player.id} className="px-3 py-2 flex items-center gap-3">
                <input
                  inputMode="numeric"
                  pattern="[0-9]*"
                  value={rec.jerseyNumber ?? ""}
                  onChange={(e) => {
                    const v = e.target.value.replace(/\D/g, "");
                    onSetJersey(player.id, v ? Number(v) : null);
                  }}
                  className={`w-12 h-10 rounded-full text-center font-bold text-sm border-2 ${
                    rec.present && (rec.jerseyNumber === null || rec.jerseyNumber === undefined)
                      ? "border-danger"
                      : "border-surface-100"
                  }`}
                  placeholder="—"
                  disabled={!rec.present}
                />
                <div className="flex-1">
                  <div className="font-medium text-sm">{player.fullName}</div>
                  <div className="text-xs space-x-1">
                    {player.status === "suspenso" && (
                      <span className="text-danger">⚠ suspenso</span>
                    )}
                    {goalkeeperId === player.id && (
                      <span className="text-success">goleiro</span>
                    )}
                    {rec.absenceType && (
                      <span
                        className={
                          rec.absenceType === "justificada"
                            ? "text-success"
                            : "text-danger"
                        }
                      >
                        {rec.absenceType}
                      </span>
                    )}
                  </div>
                </div>
                <button
                  onClick={() => onTogglePresence(rec)}
                  className={`px-3 py-2 rounded text-xs font-semibold touch-48 ${
                    rec.present
                      ? "bg-success text-white"
                      : "bg-surface-100 text-muted"
                  } ${player.status === "suspenso" ? "ring-2 ring-danger" : ""}`}
                >
                  {rec.present ? "Presente" : "Ausente"}
                </button>
              </li>
            );
          })}
      </ul>

      <div className="p-2 border-t border-surface-100 text-xs">
        <button
          onClick={() => setShowAvulso((s) => !s)}
          className="text-primary-500 font-medium"
        >
          + Goleiro avulso
        </button>
        {showAvulso && (
          <div className="mt-2 flex gap-2">
            <input
              placeholder="Nome"
              value={avulsoName}
              onChange={(e) => setAvulsoName(e.target.value)}
              className="flex-1 border border-surface-100 rounded px-2 py-1"
            />
            <input
              inputMode="numeric"
              placeholder="#"
              value={avulsoJersey}
              onChange={(e) => setAvulsoJersey(e.target.value.replace(/\D/g, ""))}
              className="w-16 border border-surface-100 rounded px-2 py-1"
            />
            <button
              onClick={() => {
                if (avulsoName && avulsoJersey) {
                  onSelectGoalkeeper(undefined, {
                    name: avulsoName,
                    jersey: Number(avulsoJersey)
                  });
                  setShowAvulso(false);
                  setAvulsoName("");
                  setAvulsoJersey("");
                }
              }}
              className="bg-primary-500 text-white px-3 rounded font-semibold"
            >
              OK
            </button>
          </div>
        )}
      </div>
    </section>
  );
}

type EventModalState =
  | { kind: "gol"; teamId: string }
  | { kind: "gol_contra"; teamId: string }
  | { kind: "cartao"; teamId: string }
  | { kind: "falta"; teamId: string }
  | { kind: "substituicao"; teamId: string }
  | { kind: "troca_goleiro"; teamId: string };

function PeriodView(props: {
  home: TeamLite;
  away: TeamLite;
  presence: PresenceLite[];
  ss: ScoresheetLite;
  regulation: RegulationData | null;
  tab: "timeline" | "presence" | "elenco";
  setTab: (t: "timeline" | "presence" | "elenco") => void;
  onTrigger: (state: EventModalState) => void;
  onDelete: (eventId: string) => void;
  onTogglePresence: (p: PresenceLite) => void;
  onSetJersey: (playerId: string, value: number | null) => void;
  onChangeGoalkeeper: (side: "home" | "away") => void;
  onEndPeriod: () => void;
  playerById: Map<string, PlayerLite & { teamId: string }>;
}) {
  const reversedTimeline = [...props.ss.timeline].reverse();
  return (
    <div className="px-3 pb-4 space-y-3">
      {/* Cards de ação por time */}
      <div className="grid grid-cols-2 gap-2">
        {[props.home, props.away].map((team) => {
          const isHome = team.id === props.home.id;
          const gkId = isHome
            ? props.ss.homeGoalkeeperPlayerId
            : props.ss.awayGoalkeeperPlayerId;
          const gkPlayer = gkId ? props.playerById.get(gkId) : null;
          const gkRec = props.ss.presence.find((p) => p.playerId === gkId);
          return (
            <div
              key={team.id}
              className="bg-white rounded-lg border border-surface-100 overflow-hidden"
            >
              <div
                className="px-2 py-2 text-white text-xs font-semibold flex justify-between items-center"
                style={{ background: team.color }}
              >
                <span className="truncate">{team.name}</span>
                <button
                  onClick={() => props.onChangeGoalkeeper(isHome ? "home" : "away")}
                  className="opacity-90 text-[10px] underline"
                >
                  {gkPlayer
                    ? `#${gkRec?.jerseyNumber ?? "—"} ${gkPlayer.fullName} ✎`
                    : "Definir goleiro"}
                </button>
              </div>
              <div className="grid grid-cols-2 gap-1 p-1">
                <button
                  onClick={() => props.onTrigger({ kind: "gol", teamId: team.id })}
                  className="touch-48 rounded text-white font-semibold py-2"
                  style={{ background: team.color }}
                >
                  Gol
                </button>
                <button
                  onClick={() => props.onTrigger({ kind: "cartao", teamId: team.id })}
                  className="touch-48 rounded bg-ink text-white py-2 text-sm font-semibold"
                >
                  Cartão
                </button>
                <button
                  onClick={() => props.onTrigger({ kind: "falta", teamId: team.id })}
                  className="touch-48 rounded bg-surface-100 text-ink py-2 text-sm font-semibold"
                >
                  Falta
                </button>
                <button
                  onClick={() => props.onTrigger({ kind: "substituicao", teamId: team.id })}
                  className="touch-48 rounded bg-surface-100 text-ink py-2 text-sm font-semibold"
                >
                  Subst.
                </button>
              </div>
            </div>
          );
        })}
      </div>

      <button
        onClick={props.onEndPeriod}
        className="w-full bg-ink text-white rounded-lg py-3 font-semibold touch-48"
      >
        Encerrar {props.ss.currentPeriod}º período
      </button>

      {/* Tabs */}
      <div className="flex gap-2 border-b border-surface-100">
        {(["timeline", "presence", "elenco"] as const).map((t) => (
          <button
            key={t}
            onClick={() => props.setTab(t)}
            className={`px-3 py-2 text-sm ${
              props.tab === t
                ? "border-b-2 border-primary-500 text-primary-700 font-semibold"
                : "text-muted"
            }`}
          >
            {t === "timeline" ? "Timeline" : t === "presence" ? "Presença" : "Elencos"}
          </button>
        ))}
      </div>

      {props.tab === "timeline" && (
        <ul className="space-y-1">
          {reversedTimeline.map((e) => {
            const player = e.playerId ? props.playerById.get(e.playerId) : null;
            const team = e.teamId === props.home.id ? props.home.name : props.away.name;
            const num = props.ss.presence.find((p) => p.playerId === e.playerId)?.jerseyNumber;
            const removable = e.type !== "inicio_periodo" && e.type !== "fim_periodo";
            return (
              <li
                key={e.id}
                className="bg-white border border-surface-100 rounded p-2 text-sm flex items-center justify-between"
              >
                <div>
                  <span className="text-xs font-mono text-muted mr-2">
                    {e.clockLabel}
                  </span>
                  <span className="font-semibold">{eventTypeLabel(e.type)}</span>
                  {player && (
                    <span className="ml-1">
                      — #{num ?? "?"} {player.fullName}
                    </span>
                  )}
                  <span className="text-muted text-xs"> · {team}</span>
                  {e.autoGeneratedFromId && (
                    <span className="ml-1 text-[10px] text-alert">automático</span>
                  )}
                </div>
                {removable && (
                  <button
                    onClick={() => props.onDelete(e.id)}
                    className="text-danger text-xs"
                  >
                    Excluir
                  </button>
                )}
              </li>
            );
          })}
        </ul>
      )}

      {props.tab === "presence" && (
        <div className="space-y-3">
          {[props.home, props.away].map((team) => (
            <PresenceTeamSection
              key={team.id}
              team={team}
              presence={props.ss.presence}
              goalkeeperId={
                team.id === props.home.id
                  ? props.ss.homeGoalkeeperPlayerId
                  : props.ss.awayGoalkeeperPlayerId
              }
              onTogglePresence={props.onTogglePresence}
              onSetJersey={props.onSetJersey}
              onSelectGoalkeeper={() => undefined}
            />
          ))}
        </div>
      )}

      {props.tab === "elenco" && (
        <div className="space-y-3">
          {[props.home, props.away].map((team) => (
            <div
              key={team.id}
              className="bg-white border border-surface-100 rounded p-3"
            >
              <div className="font-semibold mb-1">{team.name}</div>
              <ul className="text-sm">
                {team.players.map((p) => {
                  const rec = props.ss.presence.find((x) => x.playerId === p.id);
                  return (
                    <li key={p.id}>
                      #{rec?.jerseyNumber ?? "—"} {p.fullName}{" "}
                      {rec?.present ? "" : "(ausente)"}
                    </li>
                  );
                })}
              </ul>
            </div>
          ))}
        </div>
      )}

      {props.regulation?.foulIndividualEnabled && (
        <FoulIndividualPanel
          ss={props.ss}
          home={props.home}
          away={props.away}
          limit={props.regulation.foulIndividualLimit ?? 5}
          playerById={props.playerById}
        />
      )}
    </div>
  );
}

function FoulIndividualPanel({
  ss,
  home,
  away,
  limit,
  playerById
}: {
  ss: ScoresheetLite;
  home: TeamLite;
  away: TeamLite;
  limit: number;
  playerById: Map<string, PlayerLite & { teamId: string }>;
}) {
  const all = [...home.players, ...away.players];
  const counts = all.map((p) => ({
    player: p,
    count: countPlayerFoulsInMatch(ss.timeline as any, p.id)
  }));
  return (
    <details className="bg-white rounded border border-surface-100 p-3">
      <summary className="cursor-pointer font-semibold text-sm">
        Faltas por jogador (limite {limit})
      </summary>
      <ul className="text-sm mt-2 grid grid-cols-2 gap-1">
        {counts
          .filter((c) => c.count > 0)
          .map((c) => (
            <li
              key={c.player.id}
              className={
                c.count >= limit
                  ? "text-danger font-semibold"
                  : c.count >= limit - 1
                    ? "text-alert"
                    : ""
              }
            >
              {c.player.fullName}: {c.count}
            </li>
          ))}
      </ul>
    </details>
  );
}

function PenaltyView({
  ss,
  home,
  away,
  regulation,
  onRecord,
  onUndo,
  onConfirm
}: {
  ss: ScoresheetLite;
  home: TeamLite;
  away: TeamLite;
  regulation: RegulationData | null;
  onRecord: (teamId: string, playerId: string, converted: boolean) => Promise<void>;
  onUndo: () => Promise<void>;
  onConfirm: () => Promise<void>;
}) {
  const [selected, setSelected] = useState<string | null>(null);
  const kicks = ss.penaltyShoot?.kicks ?? [];
  const kicksPerTeam = regulation?.penaltyKicksPerTeam ?? 5;

  const state = computePenaltyState({
    kicks: kicks as any,
    homeTeamId: home.id,
    awayTeamId: away.id,
    kicksPerTeam
  });
  const currentTeam = state.nextTeamId === home.id ? home : away;
  const presents = ss.presence.filter(
    (p) =>
      p.present &&
      (state.nextTeamId === home.id
        ? home.players.find((x) => x.id === p.playerId)
        : away.players.find((x) => x.id === p.playerId))
  );

  return (
    <div className="px-4 py-4 space-y-4">
      <div className="bg-white rounded-lg border border-surface-100 p-4 text-center">
        <p className="text-xs text-muted">Disputa de pênaltis</p>
        <div className="text-3xl font-bold tabular-nums my-2">
          {state.homeScore} × {state.awayScore}
        </div>
        <div className="grid grid-cols-2 gap-3 mt-3">
          {[home, away].map((team) => {
            const teamKicks = kicks.filter((k) => k.teamId === team.id);
            return (
              <div key={team.id}>
                <div className="text-xs font-semibold mb-1">{team.name}</div>
                <div className="flex gap-1 justify-center">
                  {Array.from({ length: kicksPerTeam }).map((_, i) => {
                    const kick = teamKicks[i];
                    if (!kick) {
                      return (
                        <span
                          key={i}
                          className="w-5 h-5 rounded-full bg-surface-100"
                        />
                      );
                    }
                    return (
                      <span
                        key={i}
                        className={`w-5 h-5 rounded-full text-white text-xs font-bold flex items-center justify-center ${
                          kick.converted ? "bg-success" : "bg-danger"
                        }`}
                      >
                        {kick.converted ? "✓" : "✗"}
                      </span>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {!state.finished && (
        <div className="bg-white rounded-lg border border-surface-100 p-4 space-y-3">
          <div className="text-sm">
            {state.nextKickOrder}ª cobrança — <strong>{currentTeam.name}</strong>
          </div>
          <select
            value={selected ?? ""}
            onChange={(e) => setSelected(e.target.value || null)}
            className="w-full border border-surface-100 rounded px-3 py-2"
          >
            <option value="">Selecione o cobrador…</option>
            {presents.map((p) => {
              const player = currentTeam.players.find((x) => x.id === p.playerId)!;
              return (
                <option key={p.playerId} value={p.playerId}>
                  #{p.jerseyNumber ?? "—"} {player.fullName}
                </option>
              );
            })}
          </select>
          <div className="grid grid-cols-2 gap-2">
            <button
              disabled={!selected}
              onClick={() => selected && onRecord(currentTeam.id, selected, true)}
              className="rounded bg-success text-white py-3 font-semibold disabled:opacity-40"
            >
              Converteu
            </button>
            <button
              disabled={!selected}
              onClick={() => selected && onRecord(currentTeam.id, selected, false)}
              className="rounded bg-danger text-white py-3 font-semibold disabled:opacity-40"
            >
              Errou
            </button>
          </div>
          {kicks.length > 0 && (
            <button
              onClick={onUndo}
              className="w-full rounded bg-surface-100 py-2 text-sm font-semibold"
            >
              Desfazer última cobrança
            </button>
          )}
        </div>
      )}

      {state.finished && state.winnerTeamId && (
        <div className="bg-white rounded-lg border border-surface-100 p-4 text-center space-y-3">
          <div className="text-success font-bold">
            {state.winnerTeamId === home.id ? home.name : away.name} vence nos pênaltis
          </div>
          <div className="text-sm text-muted">
            {state.homeScore} × {state.awayScore}
          </div>
          <button
            onClick={onConfirm}
            className="w-full rounded bg-primary-500 text-white py-3 font-semibold"
          >
            Confirmar resultado
          </button>
        </div>
      )}
    </div>
  );
}

function ReviewView(props: {
  ss: ScoresheetLite;
  home: TeamLite;
  away: TeamLite;
  championshipName: string;
  refereeName: string | null;
  homeResponsible: string | null;
  awayResponsible: string | null;
  scheduledAt: string;
  venue: string | null;
  playerById: Map<string, PlayerLite & { teamId: string }>;
  onBack: () => void;
  onSave: () => void;
  onRegisterOccurrence: () => void;
}) {
  return (
    <div className="px-4 py-4 space-y-3">
      <h2 className="text-lg font-bold">Revisão</h2>
      <div className="bg-white rounded-lg p-4 border border-surface-100">
        <div className="text-sm text-muted">{props.championshipName}</div>
        <div className="text-2xl font-bold my-2">
          {props.home.name} {props.ss.homeScore} × {props.ss.awayScore} {props.away.name}
        </div>
        {props.ss.penaltyShoot && (
          <div className="text-sm">
            Pênaltis: {props.ss.penaltyShoot.homeScore} × {props.ss.penaltyShoot.awayScore}
          </div>
        )}
        <div className="text-sm space-y-1 mt-2">
          {props.refereeName && <div>Árbitro: {props.refereeName}</div>}
          {props.homeResponsible && (
            <div>Resp. {props.home.name}: {props.homeResponsible}</div>
          )}
          {props.awayResponsible && (
            <div>Resp. {props.away.name}: {props.awayResponsible}</div>
          )}
        </div>
      </div>

      <details className="bg-white rounded-lg p-3 border border-surface-100">
        <summary className="font-semibold">Timeline</summary>
        <ul className="text-sm mt-2 space-y-0.5">
          {props.ss.timeline.map((e) => {
            const player = e.playerId ? props.playerById.get(e.playerId) : null;
            const team = e.teamId === props.home.id ? props.home.name : props.away.name;
            return (
              <li key={e.id}>
                <span className="font-mono mr-1">{e.clockLabel}</span>
                {eventTypeLabel(e.type)}{player ? ` — ${player.fullName}` : ""} ({team})
              </li>
            );
          })}
        </ul>
      </details>

      <div className="grid grid-cols-2 gap-2">
        <button
          onClick={props.onBack}
          className="rounded bg-surface-100 py-3 font-semibold"
        >
          Voltar
        </button>
        <button
          onClick={props.onRegisterOccurrence}
          className="rounded bg-alert text-white py-3 font-semibold"
        >
          Registrar ocorrência
        </button>
      </div>
      <button
        onClick={props.onSave}
        className="w-full rounded bg-primary-500 text-white py-4 text-lg font-semibold"
      >
        Salvar súmula
      </button>
    </div>
  );
}

// ============================================================
// MODAIS
// ============================================================

function AbsenceModal({
  player,
  onConfirm,
  onClose
}: {
  player: (PlayerLite & { teamId: string }) | null;
  onConfirm: (absenceType: "justificada" | "injustificada") => void;
  onClose: () => void;
}) {
  const [choice, setChoice] = useState<"justificada" | "injustificada" | null>(null);
  return (
    <ModalShell onClose={onClose}>
      <h3 className="font-semibold mb-2">{player?.fullName ?? "Ausência"}</h3>
      <div className="grid gap-2 mb-3">
        <button
          onClick={() => setChoice("justificada")}
          className={`rounded py-3 font-semibold border ${
            choice === "justificada"
              ? "bg-success text-white border-success"
              : "border-surface-100"
          }`}
        >
          Ausência justificada
        </button>
        <button
          onClick={() => setChoice("injustificada")}
          className={`rounded py-3 font-semibold border ${
            choice === "injustificada"
              ? "bg-danger text-white border-danger"
              : "border-surface-100"
          }`}
        >
          Ausência injustificada
        </button>
      </div>
      <button
        disabled={!choice}
        onClick={() => choice && onConfirm(choice)}
        className="w-full bg-primary-500 text-white py-3 rounded font-semibold disabled:opacity-40"
      >
        Confirmar ausência
      </button>
    </ModalShell>
  );
}

function EventModal(props: {
  state: EventModalState;
  ss: ScoresheetLite;
  home: TeamLite;
  away: TeamLite;
  regulation: RegulationData | null;
  playerById: Map<string, PlayerLite & { teamId: string }>;
  onClose: () => void;
  onConfirm: (args: {
    type: string;
    teamId: string;
    playerId?: string | null;
    secondaryPlayerId?: string | null;
  }) => Promise<void>;
}) {
  const team = props.state.teamId === props.home.id ? props.home : props.away;
  const presents = props.ss.presence.filter(
    (p) => p.present && team.players.find((x) => x.id === p.playerId)
  );
  const [playerId, setPlayerId] = useState<string | null>(null);
  const [secondaryId, setSecondaryId] = useState<string | null>(null);
  const [cardType, setCardType] = useState<"cartao_amarelo" | "cartao_vermelho" | "cartao_azul">(
    "cartao_amarelo"
  );

  let title = "";
  let needsPlayer = true;
  let onSubmit: () => Promise<void>;

  if (props.state.kind === "gol") {
    title = `Gol — ${team.name}`;
    onSubmit = () =>
      props.onConfirm({ type: "gol", teamId: team.id, playerId });
  } else if (props.state.kind === "gol_contra") {
    title = `Gol contra — ${team.name}`;
    onSubmit = () =>
      props.onConfirm({ type: "gol_contra", teamId: team.id, playerId });
  } else if (props.state.kind === "cartao") {
    title = `Cartão — ${team.name}`;
    onSubmit = () =>
      props.onConfirm({ type: cardType, teamId: team.id, playerId });
  } else if (props.state.kind === "falta") {
    title = `Falta — ${team.name}`;
    needsPlayer = false;
    onSubmit = () =>
      props.onConfirm({ type: "falta", teamId: team.id, playerId });
  } else if (props.state.kind === "substituicao") {
    title = `Substituição — ${team.name}`;
    onSubmit = () =>
      props.onConfirm({
        type: "substituicao",
        teamId: team.id,
        playerId,
        secondaryPlayerId: secondaryId
      });
  } else {
    // troca_goleiro
    title = `Troca de goleiro — ${team.name}`;
    onSubmit = () =>
      props.onConfirm({ type: "troca_goleiro", teamId: team.id, playerId });
  }

  return (
    <ModalShell onClose={props.onClose}>
      <h3 className="font-semibold mb-3">{title}</h3>

      {props.state.kind === "cartao" && (
        <div className="grid grid-cols-3 gap-2 mb-3">
          <button
            onClick={() => setCardType("cartao_amarelo")}
            className={`rounded py-2 font-semibold ${
              cardType === "cartao_amarelo" ? "bg-alert text-white" : "bg-surface-100"
            }`}
          >
            Amarelo
          </button>
          <button
            onClick={() => setCardType("cartao_vermelho")}
            className={`rounded py-2 font-semibold ${
              cardType === "cartao_vermelho" ? "bg-danger text-white" : "bg-surface-100"
            }`}
          >
            Vermelho
          </button>
          {props.regulation?.cardTypes === "com_azul" && (
            <button
              onClick={() => setCardType("cartao_azul")}
              className={`rounded py-2 font-semibold ${
                cardType === "cartao_azul" ? "bg-primary-500 text-white" : "bg-surface-100"
              }`}
            >
              Azul
            </button>
          )}
        </div>
      )}

      {(needsPlayer || props.state.kind === "falta") && (
        <select
          value={playerId ?? ""}
          onChange={(e) => setPlayerId(e.target.value || null)}
          className="w-full border border-surface-100 rounded px-3 py-2 mb-3"
        >
          <option value="">
            {props.state.kind === "falta" ? "Jogador (opcional)" : "Selecione o jogador"}
          </option>
          {presents.map((p) => {
            const player = team.players.find((x) => x.id === p.playerId)!;
            return (
              <option key={p.playerId} value={p.playerId}>
                #{p.jerseyNumber ?? "—"} {player.fullName}
              </option>
            );
          })}
        </select>
      )}

      {props.state.kind === "substituicao" && (
        <select
          value={secondaryId ?? ""}
          onChange={(e) => setSecondaryId(e.target.value || null)}
          className="w-full border border-surface-100 rounded px-3 py-2 mb-3"
        >
          <option value="">Jogador que entra</option>
          {presents
            .filter((p) => p.playerId !== playerId)
            .map((p) => {
              const player = team.players.find((x) => x.id === p.playerId)!;
              return (
                <option key={p.playerId} value={p.playerId}>
                  #{p.jerseyNumber ?? "—"} {player.fullName}
                </option>
              );
            })}
        </select>
      )}

      <button
        onClick={onSubmit}
        disabled={
          (needsPlayer && !playerId) ||
          (props.state.kind === "substituicao" && !secondaryId)
        }
        className="w-full rounded bg-primary-500 text-white py-3 font-semibold disabled:opacity-40"
      >
        Confirmar
      </button>
    </ModalShell>
  );
}

function ConfirmModal({
  title,
  message,
  confirmLabel,
  danger,
  onConfirm,
  onCancel
}: {
  title: string;
  message: string;
  confirmLabel: string;
  danger: boolean;
  onConfirm: () => void;
  onCancel: () => void;
}) {
  return (
    <ModalShell onClose={onCancel}>
      <h3 className="font-semibold mb-2">{title}</h3>
      <p className="text-sm text-muted mb-4">{message}</p>
      <div className="flex gap-2">
        <button
          onClick={onCancel}
          className="flex-1 rounded bg-surface-100 py-3 font-semibold"
        >
          Cancelar
        </button>
        <button
          onClick={onConfirm}
          className={`flex-1 rounded py-3 font-semibold text-white ${
            danger ? "bg-danger" : "bg-primary-500"
          }`}
        >
          {confirmLabel}
        </button>
      </div>
    </ModalShell>
  );
}

function OccurrenceModal({
  players,
  onClose,
  onConfirm
}: {
  players: PlayerLite[];
  onClose: () => void;
  onConfirm: (type: string, description: string, players: string[]) => void;
}) {
  const [type, setType] = useState("briga");
  const [description, setDescription] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  return (
    <ModalShell onClose={onClose}>
      <h3 className="font-semibold mb-3">Registrar ocorrência</h3>
      <select
        value={type}
        onChange={(e) => setType(e.target.value)}
        className="w-full border border-surface-100 rounded px-3 py-2 mb-3"
      >
        <option value="briga">Briga</option>
        <option value="lesao">Lesão</option>
        <option value="invasao_campo">Invasão de campo</option>
        <option value="outros">Outros</option>
      </select>
      <textarea
        placeholder="Descrição"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        rows={4}
        className="w-full border border-surface-100 rounded px-3 py-2 mb-3"
      />
      <select
        multiple
        value={selected}
        onChange={(e) =>
          setSelected(Array.from(e.target.selectedOptions, (o) => o.value))
        }
        className="w-full border border-surface-100 rounded px-3 py-2 mb-3 h-28"
      >
        {players.map((p) => (
          <option key={p.id} value={p.id}>
            {p.fullName}
          </option>
        ))}
      </select>
      <button
        onClick={() => onConfirm(type, description, selected)}
        disabled={!description.trim()}
        className="w-full rounded bg-primary-500 text-white py-3 font-semibold disabled:opacity-40"
      >
        Salvar ocorrência
      </button>
    </ModalShell>
  );
}

function ModalShell({
  children,
  onClose
}: {
  children: React.ReactNode;
  onClose: () => void;
}) {
  return (
    <div className="fixed inset-0 z-30 flex items-end sm:items-center justify-center bg-black/40">
      <div className="bg-white w-full max-w-md rounded-t-2xl sm:rounded-2xl p-4">
        <div className="flex justify-end mb-1">
          <button onClick={onClose} aria-label="Fechar" className="text-muted">
            ✕
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

// ============================================================
// HELPERS
// ============================================================

function eventTypeLabel(t: string) {
  return (
    {
      gol: "Gol",
      gol_contra: "Gol contra",
      cartao_amarelo: "Cartão amarelo",
      cartao_vermelho: "Cartão vermelho",
      cartao_azul: "Cartão azul",
      falta: "Falta",
      substituicao: "Substituição",
      troca_goleiro: "Troca de goleiro",
      inicio_periodo: "Início de período",
      fim_periodo: "Fim de período"
    } as Record<string, string>
  )[t] ?? t;
}

function defaultEmptyScoresheet(): ScoresheetLite {
  return {
    id: "",
    status: "em_andamento",
    uiState: "pre_jogo",
    currentPeriod: 0,
    periodStartedAt: null,
    homeScore: 0,
    awayScore: 0,
    homeGoalkeeperPlayerId: null,
    awayGoalkeeperPlayerId: null,
    homeGoalkeeperAvulso: null,
    awayGoalkeeperAvulso: null,
    presence: [],
    timeline: [],
    penaltyShoot: null,
    shareDocText: null
  };
}

function serialize(s: any): ScoresheetLite {
  return {
    id: s.id,
    status: s.status,
    uiState: s.uiState,
    currentPeriod: s.currentPeriod,
    periodStartedAt: s.periodStartedAt
      ? typeof s.periodStartedAt === "string"
        ? s.periodStartedAt
        : new Date(s.periodStartedAt).toISOString()
      : null,
    homeScore: s.homeScore,
    awayScore: s.awayScore,
    homeGoalkeeperPlayerId: s.homeGoalkeeperPlayerId,
    awayGoalkeeperPlayerId: s.awayGoalkeeperPlayerId,
    homeGoalkeeperAvulso: s.homeGoalkeeperAvulsoName
      ? { name: s.homeGoalkeeperAvulsoName, jersey: s.homeGoalkeeperAvulsoJersey ?? 0 }
      : null,
    awayGoalkeeperAvulso: s.awayGoalkeeperAvulsoName
      ? { name: s.awayGoalkeeperAvulsoName, jersey: s.awayGoalkeeperAvulsoJersey ?? 0 }
      : null,
    presence: (s.presenceRecords ?? s.presence ?? []).map((p: any) => ({
      playerId: p.playerId,
      jerseyNumber: p.jerseyNumber,
      present: p.present,
      absenceType: p.absenceType,
      isGoalkeeper: p.isGoalkeeper
    })),
    timeline: (s.timelineEvents ?? s.timeline ?? []).map((e: any) => ({
      id: e.id,
      type: e.type,
      clockLabel: e.clockLabel,
      playerId: e.playerId,
      teamId: e.teamId,
      secondaryPlayerId: e.secondaryPlayerId,
      period: e.period,
      autoGeneratedFromId: e.autoGeneratedFromId,
      recordedAt:
        typeof e.recordedAt === "string"
          ? e.recordedAt
          : new Date(e.recordedAt).toISOString()
    })),
    penaltyShoot: s.penaltyShoot
      ? {
          homeScore: s.penaltyShoot.homeScore,
          awayScore: s.penaltyShoot.awayScore,
          finished: s.penaltyShoot.finished,
          kicks: s.penaltyShoot.kicks.map((k: any) => ({
            id: k.id,
            teamId: k.teamId,
            playerId: k.playerId,
            kickOrder: k.kickOrder,
            converted: k.converted
          }))
        }
      : null,
    shareDocText: s.shareDocText ?? null
  };
}
