// Tipos compartilhados — domínio puro, sem dependência de infra.

export type Id = string;

export type Modality = "futsal" | "suico" | "campo";

export type UserRole = "ORGANIZER" | "REFEREE";

export type ChampionshipStatus = "em_andamento" | "encerrado";

export type MatchStatus =
  | "agendado"
  | "em_andamento"
  | "encerrado"
  | "editado"
  | "reaberto";

export type ScoresheetStatus = "em_andamento" | "em_revisao" | "salvo";

export type EventType =
  | "gol"
  | "gol_contra"
  | "cartao_amarelo"
  | "cartao_vermelho"
  | "cartao_azul"
  | "falta"
  | "substituicao"
  | "troca_goleiro"
  | "inicio_periodo"
  | "fim_periodo";

export type CardTypes = "amarelo_vermelho" | "com_azul";
export type CardBlueMode = "temporario" | "definitivo_sub";
export type GoalkeeperFormula = "media" | "absoluto" | "por_minuto";
export type PlayerStatus = "ativo" | "suspenso" | "inativo";
export type AbsenceType = "justificada" | "injustificada";

export type SuspensionReason =
  | "vermelho_direto"
  | "dois_amarelos"
  | "acumulo_amarelos";

export type TiebreakCriterion =
  | "confronto_direto"
  | "saldo_gols"
  | "gols_pro"
  | "gols_sofridos"
  | "num_vitorias"
  | "menos_cartoes"
  | "sorteio";

export interface TimelineEvent {
  id: Id;
  scoresheetId: Id;
  type: EventType;
  clockLabel: string;
  playerId?: Id | null;
  teamId: Id;
  secondaryPlayerId?: Id | null;
  period: number;
  recordedAt: Date;
  autoGeneratedFromId?: Id | null;
}

export interface PresenceRecord {
  scoresheetId: Id;
  playerId: Id;
  jerseyNumber: number | null;
  present: boolean;
  absenceType: AbsenceType | null;
  isGoalkeeper: boolean;
}

export interface PenaltyKickRecord {
  id: Id;
  penaltyShootId: Id;
  teamId: Id;
  playerId: Id | null;
  kickOrder: number;
  converted: boolean;
}

export interface RegulationData {
  numPeriods: number;
  periodDurationMin: number;
  intervalDurationMin: number;
  cardTypes: CardTypes;
  cardBlueMode: CardBlueMode | null;
  cardBlueDurationMin: number | null;
  yellowAccumulationLimit: number;
  foulFreeKickEnabled: boolean;
  foulFreeKickLimit: number;
  foulIndividualEnabled: boolean;
  foulIndividualLimit: number | null;
  penaltiesEnabled: boolean;
  penaltyKicksPerTeam: number;
  pointsPenaltyWin: number;
  pointsPenaltyLoss: number;
  pointsWin: number;
  pointsDraw: number;
  pointsLoss: number;
  tiebreakOrder: TiebreakCriterion[];
  goalkeeperRankingFormula: GoalkeeperFormula;
}
